package it.bplus.model;

/**
 * Comuni generated by hbm2java
 */
public class Comuni implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idComune;
	private Province province;
	private String nome;
	private String codIstat;
	private String idCom;
	private String cadastrialCode;


	public Comuni() {
	}
	

	public Comuni(Long idComune, Province province, String nome,
			String cadastrialCode) {
		this.idComune = idComune;
		this.province = province;
		this.nome = nome;
		this.cadastrialCode = cadastrialCode;
	}

	public Comuni(Long idComune, Province province, String nome,
			String codIstat, String idCom, String cadastrialCode) {
		this.idComune = idComune;
		this.province = province;
		this.nome = nome;
		this.codIstat = codIstat;
		this.idCom = idCom;
		this.cadastrialCode = cadastrialCode;
	}

	public Long getIdComune() {
		return this.idComune;
	}

	public void setIdComune(Long idComune) {
		this.idComune = idComune;
	}

	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCodIstat() {
		return this.codIstat;
	}

	public void setCodIstat(String codIstat) {
		this.codIstat = codIstat;
	}

	public String getIdCom() {
		return this.idCom;
	}

	public void setIdCom(String idCom) {
		this.idCom = idCom;
	}

	public String getCadastrialCode() {
		return this.cadastrialCode;
	}

	public void setCadastrialCode(String cadastrialCode) {
		this.cadastrialCode = cadastrialCode;
	}

}
