package it.bplus.model;

/**
 * Province generated by hbm2java
 */
public class Province implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idProv;
	private Regioni regioni;
	private String nome;
	private String sigla;

	public Province() {
	}

	public Province(String idProv, Regioni regioni, String sigla) {
		this.idProv = idProv;
		this.regioni = regioni;
		this.sigla = sigla;
	}

	public Province(String idProv, Regioni regioni, String nome, String sigla) {
		this.idProv = idProv;
		this.regioni = regioni;
		this.nome = nome;
		this.sigla = sigla;
	}

	public String getIdProv() {
		return this.idProv;
	}

	public void setIdProv(String idProv) {
		this.idProv = idProv;
	}

	public Regioni getRegioni() {
		return this.regioni;
	}

	public void setRegioni(Regioni regioni) {
		this.regioni = regioni;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

}
