package it.bplus.model;

/**
 * Regioni generated by hbm2java
 */
public class Regioni implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idReg;
	private Aree aree;
	private Nazioni nazioni;
	private String nome;

	public Regioni() {
	}

	public Regioni(String idReg, String nome) {
		this.idReg = idReg;
		this.nome = nome;
	}

	public Regioni(String idReg, Aree aree, Nazioni nazioni, String nome) {
		this.idReg = idReg;
		this.aree = aree;
		this.nazioni = nazioni;
		this.nome = nome;
	}

	public String getIdReg() {
		return this.idReg;
	}

	public void setIdReg(String idReg) {
		this.idReg = idReg;
	}

	public Aree getAree() {
		return this.aree;
	}

	public void setAree(Aree aree) {
		this.aree = aree;
	}

	public Nazioni getNazioni() {
		return this.nazioni;
	}

	public void setNazioni(Nazioni nazioni) {
		this.nazioni = nazioni;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}


}
