package it.bplus.model;

// Generated 31-mar-2011 10.51.22 by Hibernate Tools 3.4.0.CR1

/**
 * RuoliId generated by hbm2java
 */
public class RuoliId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String ruolo;
	private String username;

	public RuoliId() {
	}

	public RuoliId(String ruolo, String username) {
		this.ruolo = ruolo;
		this.username = username;
	}

	public String getRuolo() {
		return this.ruolo;
	}

	public void setRuolo(String ruolo) {
		this.ruolo = ruolo;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RuoliId))
			return false;
		RuoliId castOther = (RuoliId) other;

		return ((this.getRuolo() == castOther.getRuolo()) || (this.getRuolo() != null
				&& castOther.getRuolo() != null && this.getRuolo().equals(
				castOther.getRuolo())))
				&& ((this.getUsername() == castOther.getUsername()) || (this
						.getUsername() != null
						&& castOther.getUsername() != null && this
						.getUsername().equals(castOther.getUsername())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRuolo() == null ? 0 : this.getRuolo().hashCode());
		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		return result;
	}

}
