package it.bplus.model;

/**
 * Sistemagiocodim generated by hbm2java
 */
public class Sistemagiocodim implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long aamsGamesystemId;
	private String name;

	public Sistemagiocodim() {
		super();
	}

	public Sistemagiocodim(long aamsGamesystemId, String name) {
		this.aamsGamesystemId = aamsGamesystemId;
		this.name = name;
	}

	public long getAamsGamesystemId() {
		return this.aamsGamesystemId;
	}

	public void setAamsGamesystemId(long aamsGamesystemId) {
		this.aamsGamesystemId = aamsGamesystemId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
