package it.bplus.model;

/**
 * Nazioni generated by hbm2java
 */
public class Nazioni implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idNazione;
	private String nome;

	public Nazioni() {
	}

	public Nazioni(int idNazione, String nome) {
		this.idNazione = idNazione;
		this.nome = nome;
	}



	public int getIdNazione() {
		return this.idNazione;
	}

	public void setIdNazione(int idNazione) {
		this.idNazione = idNazione;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

}
