package it.bplus.model;

// Generated 5-apr-2011 19.46.29 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Spaziodim generated by hbm2java
 */
public class Spaziodim implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal id;
	private Province province;
	private Regioni regioni;
	private Aree aree;
	private Comuni comuni;
	private Nazioni nazioni;
	private Long gsGameId;
	private String gameName;
	private String civVlt;
	private String aamsVltId;
	private String aamsLocationId;
	private String locationName;
	private String city;
	private String codCatastoCity;
	private String district;
	private String region;
	private String zone;
	private String nation;
	private String locationAddress;
	private String cap;

	public Spaziodim() {
		super();
	}

	public Spaziodim(BigDecimal id, Province province, Regioni regioni,
			Aree aree, Comuni comuni, Nazioni nazioni) {
		this.id = id;
		this.province = province;
		this.regioni = regioni;
		this.aree = aree;
		this.comuni = comuni;
		this.nazioni = nazioni;
	}

	public Spaziodim(BigDecimal id, Province province, Regioni regioni,
			Aree aree, Comuni comuni, Nazioni nazioni, Long gsGameId,
			String gameName, String civVlt, String aamsVltId,
			String aamsLocationId, String locationName, String city,
			String codCatastoCity, String district, String region, String zone,
			String nation, String locationAddress, String cap) {
		this.id = id;
		this.province = province;
		this.regioni = regioni;
		this.aree = aree;
		this.comuni = comuni;
		this.nazioni = nazioni;
		this.gsGameId = gsGameId;
		this.gameName = gameName;
		this.civVlt = civVlt;
		this.aamsVltId = aamsVltId;
		this.aamsLocationId = aamsLocationId;
		this.locationName = locationName;
		this.city = city;
		this.codCatastoCity = codCatastoCity;
		this.district = district;
		this.region = region;
		this.zone = zone;
		this.nation = nation;
		this.locationAddress = locationAddress;
		this.cap = cap;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	public Regioni getRegioni() {
		return this.regioni;
	}

	public void setRegioni(Regioni regioni) {
		this.regioni = regioni;
	}

	public Aree getAree() {
		return this.aree;
	}

	public void setAree(Aree aree) {
		this.aree = aree;
	}

	public Comuni getComuni() {
		return this.comuni;
	}

	public void setComuni(Comuni comuni) {
		this.comuni = comuni;
	}

	public Nazioni getNazioni() {
		return this.nazioni;
	}

	public void setNazioni(Nazioni nazioni) {
		this.nazioni = nazioni;
	}

	public Long getGsGameId() {
		return this.gsGameId;
	}

	public void setGsGameId(Long gsGameId) {
		this.gsGameId = gsGameId;
	}

	public String getGameName() {
		return this.gameName;
	}

	public void setGameName(String gameName) {
		this.gameName = gameName;
	}

	public String getCivVlt() {
		return this.civVlt;
	}

	public void setCivVlt(String civVlt) {
		this.civVlt = civVlt;
	}

	public String getAamsVltId() {
		return this.aamsVltId;
	}

	public void setAamsVltId(String aamsVltId) {
		this.aamsVltId = aamsVltId;
	}

	public String getAamsLocationId() {
		return this.aamsLocationId;
	}

	public void setAamsLocationId(String aamsLocationId) {
		this.aamsLocationId = aamsLocationId;
	}

	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCodCatastoCity() {
		return this.codCatastoCity;
	}

	public void setCodCatastoCity(String codCatastoCity) {
		this.codCatastoCity = codCatastoCity;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getZone() {
		return this.zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	public String getLocationAddress() {
		return this.locationAddress;
	}

	public void setLocationAddress(String locationAddress) {
		this.locationAddress = locationAddress;
	}

	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

}
